@extends('layouts.app')

@section('title', 'مراجعة '.$serviceCenter->name.' | موثوق')

@section('content')
    <section class="min-h-[calc(100vh-4.5rem)] bg-sand-50 px-4 py-8 sm:px-6 lg:px-8">
        <div class="mx-auto max-w-6xl">
            <nav class="flex items-center gap-2 text-sm font-bold text-slate-500"><a href="{{ route('admin.dashboard') }}" class="hover:text-brand-700">لوحة الإدارة</a><span>/</span><a href="{{ route('admin.service-centers.index') }}" class="hover:text-brand-700">المراكز</a><span>/</span><span class="truncate text-ink-950">{{ $serviceCenter->name }}</span></nav>
            <header class="mt-6 rounded-[2rem] bg-ink-950 p-7 text-white sm:p-9"><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold text-brand-300">مراجعة مركز الصيانة</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">{{ $serviceCenter->name }}</h1><p class="mt-3 text-sm text-white/60">{{ $serviceCenter->address }}، {{ $serviceCenter->city->name }}</p></div><div class="flex gap-2 text-xs font-black"><span class="rounded-full bg-white/10 px-4 py-2">{{ $serviceCenter->status->label() }}</span><span class="rounded-full bg-white/10 px-4 py-2">{{ $serviceCenter->verified_at ? '✓ موثق' : 'غير موثق' }}</span></div></div></header>

            @if (session('success'))<div role="status" class="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-bold text-emerald-800">✓ {{ session('success') }}</div>@endif
            @if ($errors->any())<div role="alert" class="mt-6 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-bold text-red-700">{{ $errors->first() }}</div>@endif

            <div class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]">
                <div class="grid gap-6">
                    <section class="rounded-3xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-black text-ink-950">بيانات المركز</h2><dl class="mt-5 grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-slate-400">المالك</dt><dd class="mt-1 font-bold text-ink-950">{{ $serviceCenter->owner?->name ?: 'بدون مالك' }}</dd><dd class="text-xs text-slate-500">{{ $serviceCenter->owner?->email }}</dd></div><div><dt class="text-slate-400">الهاتف</dt><dd dir="ltr" class="mt-1 text-right font-bold text-ink-950">{{ $serviceCenter->phone }}</dd></div><div><dt class="text-slate-400">الموقع</dt><dd class="mt-1 font-bold text-ink-950">{{ $serviceCenter->city->name }}، {{ $serviceCenter->city->governorate->name }}</dd></div><div><dt class="text-slate-400">العنوان</dt><dd class="mt-1 font-bold text-ink-950">{{ $serviceCenter->address }}</dd></div></dl>@if ($serviceCenter->description)<p class="mt-5 border-t border-slate-100 pt-5 text-sm leading-8 text-slate-600">{{ $serviceCenter->description }}</p>@endif</section>
                    <section class="grid gap-6 sm:grid-cols-2"><div class="rounded-3xl border border-slate-200 bg-white p-6"><h2 class="font-black text-ink-950">الخدمات</h2><div class="mt-4 flex flex-wrap gap-2">@forelse ($serviceCenter->services as $service)<span class="rounded-xl bg-brand-50 px-3 py-2 text-xs font-bold text-brand-800">{{ $service->name }}</span>@empty<span class="text-sm text-slate-400">لم تضاف خدمات.</span>@endforelse</div></div><div class="rounded-3xl border border-slate-200 bg-white p-6"><h2 class="font-black text-ink-950">الماركات</h2><div class="mt-4 flex flex-wrap gap-2">@forelse ($serviceCenter->carBrands as $brand)<span class="rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">{{ $brand->name }}</span>@empty<span class="text-sm text-slate-400">لم تضاف ماركات.</span>@endforelse</div></div></section>
                    <section class="rounded-3xl border border-slate-200 bg-white p-6"><h2 class="font-black text-ink-950">ملخص التقييمات</h2><div class="mt-4 flex gap-8 text-sm"><span><strong class="text-2xl text-ink-950">{{ $serviceCenter->published_reviews_avg_rating ? round((float) $serviceCenter->published_reviews_avg_rating, 1) : '—' }}</strong><span class="mr-2 text-slate-400">المتوسط</span></span><span><strong class="text-2xl text-ink-950">{{ $serviceCenter->published_reviews_count }}</strong><span class="mr-2 text-slate-400">تقييم منشور</span></span></div></section>
                </div>

                <aside class="grid h-fit gap-5 lg:sticky lg:top-24">
                    <form method="POST" action="{{ route('admin.service-centers.status.update', $serviceCenter) }}" class="rounded-3xl border border-slate-200 bg-white p-5">@csrf @method('PATCH')<p class="text-xs font-black text-brand-700">حالة الظهور</p><h2 class="mt-1 text-lg font-black text-ink-950">النشر والإيقاف</h2><select name="status" class="mt-4 h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3">@foreach (App\Enums\ServiceCenterStatus::cases() as $status)<option value="{{ $status->value }}" @selected($serviceCenter->status === $status)>{{ $status->label() }}</option>@endforeach</select><button class="mt-3 h-12 w-full rounded-xl bg-ink-950 text-sm font-black text-white hover:bg-brand-700">حفظ حالة النشر</button></form>
                    <form method="POST" action="{{ route('admin.service-centers.verification.update', $serviceCenter) }}" class="rounded-3xl border border-slate-200 bg-white p-5">@csrf @method('PATCH')<p class="text-xs font-black text-brand-700">ثقة العملاء</p><h2 class="mt-1 text-lg font-black text-ink-950">حالة التوثيق</h2><select name="verified" class="mt-4 h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3"><option value="1" @selected($serviceCenter->verified_at)>موثق</option><option value="0" @selected(! $serviceCenter->verified_at)>غير موثق</option></select><button class="mt-3 h-12 w-full rounded-xl bg-brand-600 text-sm font-black text-white hover:bg-brand-500">حفظ حالة التوثيق</button></form>
                    @if ($serviceCenter->status === App\Enums\ServiceCenterStatus::Published)<a href="{{ route('service-centers.show', $serviceCenter->slug) }}" class="rounded-2xl border border-slate-200 bg-white px-5 py-4 text-center text-sm font-black text-brand-700">عرض الصفحة العامة</a>@endif
                </aside>
            </div>
        </div>
    </section>
@endsection
